// Code generated by MockGen. DO NOT EDIT.
// Source: ./mcp/service.go
//
// Generated by this command:
//
//	mockgen -source=./mcp/service.go -destination=./mcp/service_mock_test.go -package=mcp
//

// Package mcp is a generated GoMock package.
package mcp

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockcrx3service is a mock of crx3service interface.
type Mockcrx3service struct {
	ctrl     *gomock.Controller
	recorder *Mockcrx3serviceMockRecorder
	isgomock struct{}
}

// Mockcrx3serviceMockRecorder is the mock recorder for Mockcrx3service.
type Mockcrx3serviceMockRecorder struct {
	mock *Mockcrx3service
}

// NewMockcrx3service creates a new mock instance.
func NewMockcrx3service(ctrl *gomock.Controller) *Mockcrx3service {
	mock := &Mockcrx3service{ctrl: ctrl}
	mock.recorder = &Mockcrx3serviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcrx3service) EXPECT() *Mockcrx3serviceMockRecorder {
	return m.recorder
}

// UnpackTo mocks base method.
func (m *Mockcrx3service) UnpackTo(filename, dirname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpackTo", filename, dirname)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpackTo indicates an expected call of UnpackTo.
func (mr *Mockcrx3serviceMockRecorder) UnpackTo(filename, dirname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpackTo", reflect.TypeOf((*Mockcrx3service)(nil).UnpackTo), filename, dirname)
}
