// Code generated by MockGen. DO NOT EDIT.
// Source: ./mcp/service.go
//
// Generated by this command:
//
//	mockgen -source=./mcp/service.go -destination=./mcp/service_mock_test.go -package=mcp
//

// Package mcp is a generated GoMock package.
package mcp

import (
	context "context"
	rsa "crypto/rsa"
	iter "iter"
	reflect "reflect"

	crx3 "github.com/mediabuyerbot/go-crx3"
	gomock "go.uber.org/mock/gomock"
)

// Mockcrx3service is a mock of crx3service interface.
type Mockcrx3service struct {
	ctrl     *gomock.Controller
	recorder *Mockcrx3serviceMockRecorder
	isgomock struct{}
}

// Mockcrx3serviceMockRecorder is the mock recorder for Mockcrx3service.
type Mockcrx3serviceMockRecorder struct {
	mock *Mockcrx3service
}

// NewMockcrx3service creates a new mock instance.
func NewMockcrx3service(ctrl *gomock.Controller) *Mockcrx3service {
	mock := &Mockcrx3service{ctrl: ctrl}
	mock.recorder = &Mockcrx3serviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcrx3service) EXPECT() *Mockcrx3serviceMockRecorder {
	return m.recorder
}

// Base64 mocks base method.
func (m *Mockcrx3service) Base64(filename string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Base64", filename)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Base64 indicates an expected call of Base64.
func (mr *Mockcrx3serviceMockRecorder) Base64(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Base64", reflect.TypeOf((*Mockcrx3service)(nil).Base64), filename)
}

// DownloadFromWebStore mocks base method.
func (m *Mockcrx3service) DownloadFromWebStore(extensionID, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFromWebStore", extensionID, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFromWebStore indicates an expected call of DownloadFromWebStore.
func (mr *Mockcrx3serviceMockRecorder) DownloadFromWebStore(extensionID, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFromWebStore", reflect.TypeOf((*Mockcrx3service)(nil).DownloadFromWebStore), extensionID, filename)
}

// GetID mocks base method.
func (m *Mockcrx3service) GetID(filename string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID", filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *Mockcrx3serviceMockRecorder) GetID(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*Mockcrx3service)(nil).GetID), filename)
}

// PackTo mocks base method.
func (m *Mockcrx3service) PackTo(source, dest string, pk *rsa.PrivateKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackTo", source, dest, pk)
	ret0, _ := ret[0].(error)
	return ret0
}

// PackTo indicates an expected call of PackTo.
func (mr *Mockcrx3serviceMockRecorder) PackTo(source, dest, pk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackTo", reflect.TypeOf((*Mockcrx3service)(nil).PackTo), source, dest, pk)
}

// Scan mocks base method.
func (m *Mockcrx3service) Scan(rootPath string, opts ...crx3.ScanOption) iter.Seq2[*crx3.ExtensionInfo, error] {
	m.ctrl.T.Helper()
	varargs := []any{rootPath}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(iter.Seq2[*crx3.ExtensionInfo, error])
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *Mockcrx3serviceMockRecorder) Scan(rootPath any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{rootPath}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*Mockcrx3service)(nil).Scan), varargs...)
}

// SearchExtensionByName mocks base method.
func (m *Mockcrx3service) SearchExtensionByName(ctx context.Context, name string) ([]crx3.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchExtensionByName", ctx, name)
	ret0, _ := ret[0].([]crx3.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchExtensionByName indicates an expected call of SearchExtensionByName.
func (mr *Mockcrx3serviceMockRecorder) SearchExtensionByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchExtensionByName", reflect.TypeOf((*Mockcrx3service)(nil).SearchExtensionByName), ctx, name)
}

// UnpackTo mocks base method.
func (m *Mockcrx3service) UnpackTo(filename, dirname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpackTo", filename, dirname)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpackTo indicates an expected call of UnpackTo.
func (mr *Mockcrx3serviceMockRecorder) UnpackTo(filename, dirname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpackTo", reflect.TypeOf((*Mockcrx3service)(nil).UnpackTo), filename, dirname)
}

// UnzipTo mocks base method.
func (m *Mockcrx3service) UnzipTo(filename, dirname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnzipTo", filename, dirname)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnzipTo indicates an expected call of UnzipTo.
func (mr *Mockcrx3serviceMockRecorder) UnzipTo(filename, dirname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnzipTo", reflect.TypeOf((*Mockcrx3service)(nil).UnzipTo), filename, dirname)
}

// Version mocks base method.
func (m *Mockcrx3service) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *Mockcrx3serviceMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*Mockcrx3service)(nil).Version))
}

// ZipTo mocks base method.
func (m *Mockcrx3service) ZipTo(source, dest string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZipTo", source, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// ZipTo indicates an expected call of ZipTo.
func (mr *Mockcrx3serviceMockRecorder) ZipTo(source, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZipTo", reflect.TypeOf((*Mockcrx3service)(nil).ZipTo), source, dest)
}
