// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/crx3.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CrxFileHeader struct {
	// PSS signature with RSA public key. The public key is formatted as a
	// X.509 SubjectPublicKeyInfo block, as in CRX₂. In the common case of a
	// developer key proof, the first 128 bits of the SHA-256 hash of the
	// public key must equal the crx_id.
	Sha256WithRsa []*AsymmetricKeyProof `protobuf:"bytes,2,rep,name=sha256_with_rsa,json=sha256WithRsa" json:"sha256_with_rsa,omitempty"`
	// ECDSA signature, using the NIST P-256 curve. Public key appears in
	// named-curve format.
	// The pinned algorithm will be this, at least on 2017-01-01.
	Sha256WithEcdsa []*AsymmetricKeyProof `protobuf:"bytes,3,rep,name=sha256_with_ecdsa,json=sha256WithEcdsa" json:"sha256_with_ecdsa,omitempty"`
	// The binary form of a SignedData message. We do not use a nested
	// SignedData message, as handlers of this message must verify the proofs
	// on exactly these bytes, so it is convenient to parse in two steps.
	//
	// All proofs in this CrxFile message are on the value
	// "CRX3 SignedData\x00" + signed_header_size + signed_header_data +
	// archive, where "\x00" indicates an octet with value 0, "CRX3 SignedData"
	// is encoded using UTF-8, signed_header_size is the size in octets of the
	// contents of this field and is encoded using 4 octets in little-endian
	// order, signed_header_data is exactly the content of this field, and
	// archive is the remaining contents of the file following the header.
	SignedHeaderData     []byte   `protobuf:"bytes,10000,opt,name=signed_header_data,json=signedHeaderData" json:"signed_header_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrxFileHeader) Reset()         { *m = CrxFileHeader{} }
func (m *CrxFileHeader) String() string { return proto.CompactTextString(m) }
func (*CrxFileHeader) ProtoMessage()    {}
func (*CrxFileHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffbe72ecdb1edd73, []int{0}
}

func (m *CrxFileHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrxFileHeader.Unmarshal(m, b)
}
func (m *CrxFileHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrxFileHeader.Marshal(b, m, deterministic)
}
func (m *CrxFileHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrxFileHeader.Merge(m, src)
}
func (m *CrxFileHeader) XXX_Size() int {
	return xxx_messageInfo_CrxFileHeader.Size(m)
}
func (m *CrxFileHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_CrxFileHeader.DiscardUnknown(m)
}

var xxx_messageInfo_CrxFileHeader proto.InternalMessageInfo

func (m *CrxFileHeader) GetSha256WithRsa() []*AsymmetricKeyProof {
	if m != nil {
		return m.Sha256WithRsa
	}
	return nil
}

func (m *CrxFileHeader) GetSha256WithEcdsa() []*AsymmetricKeyProof {
	if m != nil {
		return m.Sha256WithEcdsa
	}
	return nil
}

func (m *CrxFileHeader) GetSignedHeaderData() []byte {
	if m != nil {
		return m.SignedHeaderData
	}
	return nil
}

type AsymmetricKeyProof struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsymmetricKeyProof) Reset()         { *m = AsymmetricKeyProof{} }
func (m *AsymmetricKeyProof) String() string { return proto.CompactTextString(m) }
func (*AsymmetricKeyProof) ProtoMessage()    {}
func (*AsymmetricKeyProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffbe72ecdb1edd73, []int{1}
}

func (m *AsymmetricKeyProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsymmetricKeyProof.Unmarshal(m, b)
}
func (m *AsymmetricKeyProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsymmetricKeyProof.Marshal(b, m, deterministic)
}
func (m *AsymmetricKeyProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsymmetricKeyProof.Merge(m, src)
}
func (m *AsymmetricKeyProof) XXX_Size() int {
	return xxx_messageInfo_AsymmetricKeyProof.Size(m)
}
func (m *AsymmetricKeyProof) XXX_DiscardUnknown() {
	xxx_messageInfo_AsymmetricKeyProof.DiscardUnknown(m)
}

var xxx_messageInfo_AsymmetricKeyProof proto.InternalMessageInfo

func (m *AsymmetricKeyProof) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AsymmetricKeyProof) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SignedData struct {
	// This is simple binary, not UTF-8 encoded mpdecimal; i.e. it is exactly
	// 16 bytes long.
	CrxId                []byte   `protobuf:"bytes,1,opt,name=crx_id,json=crxId" json:"crx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedData) Reset()         { *m = SignedData{} }
func (m *SignedData) String() string { return proto.CompactTextString(m) }
func (*SignedData) ProtoMessage()    {}
func (*SignedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffbe72ecdb1edd73, []int{2}
}

func (m *SignedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedData.Unmarshal(m, b)
}
func (m *SignedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedData.Marshal(b, m, deterministic)
}
func (m *SignedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedData.Merge(m, src)
}
func (m *SignedData) XXX_Size() int {
	return xxx_messageInfo_SignedData.Size(m)
}
func (m *SignedData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedData.DiscardUnknown(m)
}

var xxx_messageInfo_SignedData proto.InternalMessageInfo

func (m *SignedData) GetCrxId() []byte {
	if m != nil {
		return m.CrxId
	}
	return nil
}

func init() {
	proto.RegisterType((*CrxFileHeader)(nil), "pb.CrxFileHeader")
	proto.RegisterType((*AsymmetricKeyProof)(nil), "pb.AsymmetricKeyProof")
	proto.RegisterType((*SignedData)(nil), "pb.SignedData")
}

func init() { proto.RegisterFile("pb/crx3.proto", fileDescriptor_ffbe72ecdb1edd73) }

var fileDescriptor_ffbe72ecdb1edd73 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x49, 0x82, 0x42, 0xaf, 0x86, 0xea, 0x80, 0x92, 0x85, 0x42, 0x89, 0x9b, 0x6e, 0x8c,
	0x50, 0xd1, 0xa5, 0x60, 0xfd, 0xa1, 0x52, 0x10, 0x8d, 0x0b, 0x97, 0xc3, 0xcd, 0xcc, 0xd5, 0x0c,
	0xb6, 0x26, 0xdc, 0x99, 0x62, 0xf2, 0x16, 0x3e, 0x93, 0x4f, 0x26, 0xc9, 0x88, 0x0a, 0x82, 0xdb,
	0xf3, 0xf3, 0x9d, 0x03, 0x71, 0x5d, 0x1c, 0x29, 0x6e, 0x8e, 0xb3, 0x9a, 0x2b, 0x57, 0x89, 0xb0,
	0x2e, 0xd2, 0x8f, 0x00, 0xe2, 0x0b, 0x6e, 0xae, 0xcd, 0x82, 0x66, 0x84, 0x9a, 0x58, 0x9c, 0xc1,
	0xd0, 0x96, 0x38, 0x39, 0x39, 0x95, 0x6f, 0xc6, 0x95, 0x92, 0x2d, 0x26, 0xe1, 0x28, 0x1a, 0x6f,
	0x4c, 0x76, 0xb3, 0xba, 0xc8, 0xce, 0x6d, 0xbb, 0x5c, 0x92, 0x63, 0xa3, 0xe6, 0xd4, 0xde, 0x71,
	0x55, 0x3d, 0xe5, 0xb1, 0x8f, 0x3f, 0x1a, 0x57, 0xe6, 0x16, 0xc5, 0x14, 0xb6, 0x7f, 0xf7, 0x49,
	0x69, 0x8b, 0x49, 0xf4, 0x2f, 0x61, 0xf8, 0x43, 0xb8, 0xea, 0xe2, 0xe2, 0x10, 0x84, 0x35, 0xcf,
	0xaf, 0xa4, 0x65, 0xd9, 0x9f, 0x92, 0x1a, 0x1d, 0x26, 0xef, 0xb7, 0xa3, 0x60, 0xbc, 0x99, 0x6f,
	0x79, 0xcb, 0xdf, 0xbd, 0x44, 0x87, 0xe9, 0x3d, 0x88, 0xbf, 0x54, 0xb1, 0x0f, 0x50, 0xaf, 0x8a,
	0x85, 0x51, 0xf2, 0x85, 0xda, 0x24, 0xe8, 0xbb, 0x03, 0xaf, 0xcc, 0xa9, 0x15, 0x7b, 0x30, 0xe8,
	0x40, 0xe8, 0x56, 0x4c, 0x49, 0xe8, 0xdd, 0x6f, 0x21, 0x3d, 0x00, 0x78, 0xe8, 0x67, 0xba, 0x01,
	0xb1, 0x03, 0xeb, 0x8a, 0x1b, 0x69, 0xf4, 0x17, 0x66, 0x4d, 0x71, 0x73, 0xa3, 0xa7, 0xe1, 0x2c,
	0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x7c, 0xf6, 0x18, 0x54, 0x01, 0x00, 0x00,
}
